### ISSUE TITLE
Ask Dr. Chan if 2 NN or 1

### ISSUE THREAD

**Issue by julian-robledo** [Senior-Design-ECG-AI/Senior-Design-ECG-AI.github.io#3]

**Comment by nsanchez2017** [comment]
Dr. Chan suggests the following:
"focusing on the current ECG data first to set up a "pipeline"
as I discussed in our meeting in the classroom.
If you can set up a "pipeline" for the ECG data, setting up another
"pipeline" for the other data will be similar."
